version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # - node.name=elasticsearch
      # - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - 5601:5601
    networks:
      - elastic
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    # environment:
    #   ELASTICSEARCH_HOSTS: elasticsearch

volumes:
  data:
    driver: local
networks:
  elastic:
    driver: bridge